
//      !!!! NEW INTERFACE!!!
//      EVERY EXERCISE WRAPPED IN A BIG FUNCTION,
//      JUST RUN THE CODE, AND  PRESS CORRESPONDING BUTTON 
//      AND THE EXERCISE FUNCTION WILL RUN
//      NO MORE COMMENTING AND UNCOMMENTING!!!!
//      WRITE EVERY EXERCISE CODE BETWEEN THE CURLY BRACKETS
//      YOU CAN USE SAME VARIABLE NAMES BECAUSE THEY'RE FUNCTION SPECIFIC

    function mesima1(){
        console.log('mesima1');
    }

//******************************* */

    function mesima2(){
        console.log('mesima2');
    }

//******************************* */

    function mesima3(){
console.log('m3');
    }

//******************************* */    

    function mesima4(){

    }

//******************************* */

    function mesima5(){

    }

//******************************* */

    function mesima6(){

    }

//******************************* */

    function mesima7(){

    }

//******************************* */

    function mesima8(){

    }

//******************************* */

    function mesima9(){

    }

//******************************* */
    
    function mesima10(){

    }

//******************************* */
    
    